autoInstallPeers: false

allowBuilds:
  '@swc/core': true
  core-js: true
  esbuild: true
  workerd: true

auditConfig:
  ignoreGhsas:
    - GHSA-5c6j-r48x-rmvq

overrides:
  brace-expansion: 5.0.8
  fast-uri: 3.1.4
  uuid: 11.1.1

peerDependencyRules:
  ignoreMissing:
    - search-insights

patchedDependencies:
  serialize-javascript@6.0.2: patches/serialize-javascript@6.0.2.patch

minimumReleaseAgeExclude:
  - '@easyops-cn/docusaurus-search-local@0.55.3'
